backend:
  name: github
  repo: davidmcnamee/face-mask3

media_folder: static/assets
public_folder: assets

collections:
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: name, label: Name }
      - { name: stock, label: Stock, widget: number }
      - { name: description, label: Description, widget: markdown }
      - { name: photo, label: Photo, widget: image }
