backend:
  name: github
  repo: davidmcnamee/face-mask3

local_backend:
  url: http://localhost:8081/api/v1

media_folder: static/assets
public_folder: assets

collections:
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: date, label: Posted, widget: datetime }
      - { name: tag, label: Tag }
      - { name: adult, label: Adult Stock, widget: number }
      - { name: youth, label: Youth Stock, widget: number }
      - { name: photo, label: Photo, widget: image }
  - label: Pages
    name: pages
    files:
      - label: "Home Page"
        name: home
        file: "content/page-data/index.yml"
        fields:
          - { name: name, label: Page Name }
          - { name: title, label: Page Title }
          - { name: img, label: Feature Image, widget: image }
          - { name: greeting, label: Greeting }
          - { name: text, label: Explanation block, widget: markdown }
